# Association Rule 

Prepare rules for the all the data sets 
1) Try different values of support and confidence. Observe the change in number of rules for different support,confidence values
2) Change the minimum length in apriori algorithm
3) Visulize the obtained rules using different plots

In [1]:
##Import the file
import pandas as pd
import numpy as np
df= pd.read_csv("D:/Shiva Data Science/ExcelR Assignments/Association Rule/book.csv", encoding='latin1')
df

,ChildBks,YouthBks,CookBks,DoItYBks,RefBks,ArtBks,GeogBks,ItalCook,ItalAtlas,ItalArt,Florence
0,0,1,0,1,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,1,0,1,0,0,0,0
4,0,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,1,0,0,1,1,1,0,1,1
1996,0,0,0,0,0,0,0,0,0,0,0
1997,0,0,0,0,0,0,0,0,0,0,0
1998,0,0,1,0,0,0,0,0,0,0,0
1999,0,0,0,0,0,0,0,0,0,0,0

In [2]:
# Preprocessing
df.isna().sum()

ChildBks     0
YouthBks     0
CookBks      0
DoItYBks     0
RefBks       0
ArtBks       0
GeogBks      0
ItalCook     0
ItalAtlas    0
ItalArt      0
Florence     0
dtype: int64

In [3]:
df.head()

,ChildBks,YouthBks,CookBks,DoItYBks,RefBks,ArtBks,GeogBks,ItalCook,ItalAtlas,ItalArt,Florence
0,0,1,0,1,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,1,0,1,0,0,0,0
4,0,0,1,0,0,0,1,0,0,0,0

In [4]:
# Apply algorithm
# Apriori Algorithm 
!pip install apyori

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: apyori in c:\users\91879\appdata\roaming\python\python310\site-packages (1.1.2)

In [5]:
from mlxtend.frequent_patterns import apriori,association_rules
from apyori import apriori

In [6]:
frequent_itemsets = apriori(df, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)
frequent_itemsets

In [7]:
itemsets = list(frequent_itemsets)
itemsets

[RelationRecord(items=frozenset({'d', 'C'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'C'}), items_add=frozenset({'d'}), confidence=0.33333333333333337, lift=3.666666666666667), OrderedStatistic(items_base=frozenset({'d'}), items_add=frozenset({'C'}), confidence=1.0, lift=3.666666666666667)]),
 RelationRecord(items=frozenset({'i', 'C'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'C'}), items_add=frozenset({'i'}), confidence=0.33333333333333337, lift=3.666666666666667), OrderedStatistic(items_base=frozenset({'i'}), items_add=frozenset({'C'}), confidence=1.0, lift=3.666666666666667)]),
 RelationRecord(items=frozenset({'D', 'Y'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'D'}), items_add=frozenset({'Y'}), confidence=1.0, lift=5.5), OrderedStatistic(items_base=frozenset({'Y'}), items_add=frozenset({'D'}), confidence=0.5, lift=5.5)]),
 RelationRecord(items=frozenset({'c', 'F'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'F'}), items_add=frozenset({'c'}), confidence=1.0, lift=11.0), OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({'F'}), confidence=1.0, lift=11.0)]),
 RelationRecord(items=frozenset({'e', 'F'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'F'}), items_add=frozenset({'e'}), confidence=1.0, lift=3.666666666666667), OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'F'}), confidence=0.33333333333333337, lift=3.666666666666667)]),
 RelationRecord(items=frozenset({'n', 'F'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'F'}), items_add=frozenset({'n'}), confidence=1.0, lift=11.0), OrderedStatistic(items_base=frozenset({'n'}), items_add=frozenset({'F'}), confidence=1.0, lift=11.0)]),
 RelationRecord(items=frozenset({'r', 'F'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'F'}), items_add=frozenset({'r'}), confidence=1.0, lift=3.666666666666667), OrderedStatistic(items_base=frozenset({'r'}), items_add=frozenset({'F'}), confidence=0.33333333333333337, lift=3.666666666666667)]),
 RelationRecord(items=frozenset({'G', 'e'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'G'}), items_add=frozenset({'e'}), confidence=1.0, lift=3.666666666666667), OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'G'}), confidence=0.33333333333333337, lift=3.666666666666667)]),
 RelationRecord(items=frozenset({'G', 'g'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'G'}), items_add=frozenset({'g'}), confidence=1.0, lift=11.0), OrderedStatistic(items_base=frozenset({'g'}), items_add=frozenset({'G'}), confidence=1.0, lift=11.0)]),
 RelationRecord(items=frozenset({'R', 'e'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'R'}), items_add=frozenset({'e'}), confidence=1.0, lift=3.666666666666667), OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'R'}), confidence=0.33333333333333337, lift=3.666666666666667)]),
 RelationRecord(items=frozenset({'f', 'R'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'R'}), items_add=frozenset({'f'}), confidence=1.0, lift=11.0), OrderedStatistic(items_base=frozenset({'f'}), items_add=frozenset({'R'}), confidence=1.0, lift=11.0)]),
 RelationRecord(items=frozenset({'u', 'Y'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Y'}), items_add=frozenset({'u'}), confidence=0.5, lift=5.5), OrderedStatistic(items_base=frozenset({'u'}), items_add=frozenset({'Y'}), confidence=1.0, lift=5.5)]),
 RelationRecord(items=frozenset({'c', 'e'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({'e'}), confidence=1.0, lift=3.666666666666667), OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'c'}), confidence=0.33333333333333337, lift=3.666666666666667)]),
 RelationRecord(items=frozenset({'n', 'c'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({'n'}), confidence=1.0, lift=11.0), OrderedStatistic(items_base=frozenset({'n'}), items_add=frozenset({'c'}), confidence=1.0, lift=11.0)]),
 RelationRecord(items=frozenset({'c', 'r'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({'r'}), confidence=1.0, lift=3.666666666666667), OrderedStatistic(items_base=frozenset({'r'}), items_add=frozenset({'c'}), confidence=0.33333333333333337, lift=3.666666666666667)]),
 RelationRecord(items=frozenset({'h', 'd'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'d'}), items_add=frozenset({'h'}), confidence=1.0, lift=5.5), OrderedStatistic(items_base=frozenset({'h'}), items_add=frozenset({'d'}), confidence=0.5, lift=5.5)]),
 RelationRecord(items=frozenset({'i', 'd'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'d'}), items_add=frozenset({'i'}), confidence=1.0, lift=11.0), OrderedStatistic(items_base=frozenset({'i'}), items_add=frozenset({'d'}), confidence=1.0, lift=11.0)]),
 RelationRecord(items=frozenset({'f', 'e'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'f'}), confidence=0.33333333333333337, lift=3.666666666666667), OrderedStatistic(items_base=frozenset({'f'}), items_add=frozenset({'e'}), confidence=1.0, lift=3.666666666666667)]),
 RelationRecord(items=frozenset({'g', 'e'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'g'}), confidence=0.33333333333333337, lift=3.666666666666667), OrderedStatistic(items_base=frozenset({'g'}), items_add=frozenset({'e'}), confidence=1.0, lift=3.666666666666667)]),
 RelationRecord(items=frozenset({'n', 'e'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'n'}), confidence=0.33333333333333337, lift=3.666666666666667), OrderedStatistic(items_base=frozenset({'n'}), items_add=frozenset({'e'}), confidence=1.0, lift=3.666666666666667)]),
 RelationRecord(items=frozenset({'h', 'i'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'h'}), items_add=frozenset({'i'}), confidence=0.5, lift=5.5), OrderedStatistic(items_base=frozenset({'i'}), items_add=frozenset({'h'}), confidence=1.0, lift=5.5)]),
 RelationRecord(items=frozenset({'h', 'u'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'h'}), items_add=frozenset({'u'}), confidence=0.5, lift=5.5), OrderedStatistic(items_base=frozenset({'u'}), items_add=frozenset({'h'}), confidence=1.0, lift=5.5)]),
 RelationRecord(items=frozenset({'n', 'r'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'n'}), items_add=frozenset({'r'}), confidence=1.0, lift=3.666666666666667), OrderedStatistic(items_base=frozenset({'r'}), items_add=frozenset({'n'}), confidence=0.33333333333333337, lift=3.666666666666667)])]

In [8]:
itemsets[2]

RelationRecord(items=frozenset({'D', 'Y'}), support=0.09090909090909091, ordered_statistics=[OrderedStatistic(items_base=frozenset({'D'}), items_add=frozenset({'Y'}), confidence=1.0, lift=5.5), OrderedStatistic(items_base=frozenset({'Y'}), items_add=frozenset({'D'}), confidence=0.5, lift=5.5)])

In [9]:
len(itemsets)

23

In [10]:
# Access an element from apriori table

In [11]:
itemsets[0][1] # support

0.09090909090909091

In [12]:
itemsets[0][2][0][0] # base item

frozenset({'C'})

In [13]:
itemsets[0][2][0][1] # add item

frozenset({'d'})

In [14]:
itemsets[0][2][0][2] # confidence

0.33333333333333337

In [15]:
itemsets[0][2][0][3] # lift

3.666666666666667

In [16]:
# Access through for loop
a=[]
b=[]
c=[]
d=[]
e=[]

for i in range(0,23):
    a.append(itemsets[i][1]) # support
    b.append(itemsets[i][2][0][0]) # base item
    c.append(itemsets[i][2][0][1]) # add item
    d.append(itemsets[i][2][0][2]) # confidence
    e.append(itemsets[i][2][0][3]) # lift

In [17]:
df["Support"]  = pd.DataFrame(a)
df["Baseitem"]  = pd.DataFrame(b)
df["Additem"]  = pd.DataFrame(c)
df["Confidence"]  = pd.DataFrame(d)
df["Lift"]  = pd.DataFrame(e)
df

,ChildBks,YouthBks,CookBks,DoItYBks,RefBks,ArtBks,GeogBks,ItalCook,ItalAtlas,ItalArt,Florence,Support,Baseitem,Additem,Confidence,Lift
0,0,1,0,1,0,0,1,0,0,0,0,0.090909,C,d,0.333333,3.666667
1,1,0,0,0,0,0,0,0,0,0,0,0.090909,C,i,0.333333,3.666667
2,0,0,0,0,0,0,0,0,0,0,0,0.090909,D,Y,1.000000,5.500000
3,1,1,1,0,1,0,1,0,0,0,0,0.090909,F,c,1.000000,11.000000
4,0,0,1,0,0,0,1,0,0,0,0,0.090909,F,e,1.000000,3.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,1,0,0,1,1,1,0,1,1,NaN,NaN,NaN,NaN,NaN
1996,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN
1997,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN
1998,0,0,1,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN
1999,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN